export const meitingChildrenDayConfig = [
    {
        text: "给美婷小朋友的儿童节小陪伴",
        effect: "fade",
        duration: 3300,
        music: "/static/uploads/music/夏日心动.mp3"
    },
    { text: "美婷，儿童节快乐哦。", effect: "fade", duration: 3300 },
    { text: "这是我们二十三岁的儿童节。", effect: "fade", duration: 3300 },
    { text: "想了很久，还是决定给你准备这份小小的心意。", effect: "fade", duration: 5000 },
    { text: "美婷，美婷", effect: "fade", duration: 3300 },
    { text: "美 是容颜温婉，心地纯善", effect: "fade", duration: 3300 },
    { text: "婷 是亭亭而立，温柔端庄", effect: "fade", duration: 3300 },
    { text: "你的名字轻柔又清甜，像你的声音一样好听。", effect: "fade", duration: 6000 },
    { text: "说什么好呢？", effect: "fade", duration: 3000 },
    { text: "今年我们都二十三了，总想起方大同的《才二十三》。", effect: "fade", duration: 5000, music: "/static/uploads/music/才二十三.mp3" },
    { text: "时间等不了人，生活中一不留神，转个眼秒杀了，随秒针蒸发了。", effect: "fade", duration: 7000 },
    { text: "你听过这首歌吧？", effect: "fade", duration: 3300 },
    { text: "一转眼我也要毕业了，距离上次见你，已经过去整整四年。", effect: "fade", duration: 6000 },
    { text: "可在我记忆里，你永远是那个大大咧咧、没心没肺的小孩子。", effect: "fade", duration: 7000 },
    { text: "「小孩子不好吗？」", effect: "fade", duration: 3300 },
    { text: "当然好啊。", effect: "fade", duration: 3300 },
    { text: "我希望你永远都能像个小孩子一样", effect: "fade", duration: 5000 },
    { text: "永远年轻，永远坦荡", effect: "fade", duration: 5000 },
    { text: "不用故作坚强地面对这个世界。", effect: "fade", duration: 5000 },
    { text: "「岁月 眨眼就过了」", effect: "fade", duration: 4000 },
    { text: "你总说我念旧。", effect: "fade", duration: 3300 },
    { text: "可我想，如果没有生活的压力，我们大概都会念旧吧。", effect: "fade", duration: 7000 },
    { text: "又或许…… 我其实根本不念旧。", effect: "fade", duration: 4500 },
    { text: "我只是想把生命里那些", effect: "fade", duration: 3300 },
    { text: "开心的、怀念的", effect: "fade", duration: 3300 },
    { text: "热烈的、刻骨铭心的人和事，", effect: "fade", duration: 3300 }, { text: "细细打磨、好好篆刻，安安稳稳地放进心里。", effect: "fade", duration: 5000 },
    { text: "我的心会一直保持干净，任凭时光流逝，这些珍贵的碎片也永远不会褪色。", effect: "fade", duration: 7000 },
    { text: "「上一次看 才二十三」", effect: "fade", duration: 3300 },
    { text: "「现在的日子没有那么简单」", effect: "fade", duration: 3300 },
    { text: "是啊，现在的日子，真的没有那么简单了。", effect: "fade", duration: 4000 },
    { text: "我常常在想，美婷为什么总是一个人呢？", effect: "fade", duration: 6000 },
    { text: "前阵子我压力大想和你随便说说，才发现你都不怎么会安慰人。", effect: "fade", duration: 3800 },
    { text: "你早就习惯了什么事都自己扛，什么情绪都自己消化。", effect: "fade", duration: 4500 },
    { text: "为什么会这样呢？", effect: "fade", duration: 3300 },
    { text: "或许你也曾期待过有人能拉你一把，有人能听你说说话，可真正能帮到你的人太少了。", effect: "fade", duration: 7000 },
    { text: "所以从很久以前开始，你就学会了凡事只能靠自己，于是再也不愿开口吗，因为说了，也很少有人能真正懂你、安慰你。", effect: "fade", duration: 8000 },
    { text: "还记得那年，你好像说你被调剂到了汽修专业。", effect: "fade", duration: 5000 },
    { text: "我在教学楼楼顶自习，远远看见你一个人坐在那里。", effect: "fade", duration: 5000 },
    { text: "你嘴角带着着苦笑，勉强吐出一句 \"没什么事\"，可眼睛里明明盛满了悲伤。", effect: "fade", duration: 3300 },
    { text: "我隔着窗户的铁栏想上前安慰你，却不知道怎么开口，终究什么都没说", effect: "fade", duration: 6000 },
    { text: "后来高考结束，你说家里人不同意你复读。", effect: "fade", duration: 5000 },
    { text: "我心里也跟着难受了好久，", effect: "fade", duration: 3300 },
    { text: "偷偷想着：如果你能复读就好了，我们就能一起并肩作战，", effect: "fade", duration: 4500 },
    { text: "我可以教你做题，陪你刷题，看着你一点点进步，考到你真正想去的大学。", effect: "fade", duration: 6000 },
    { text: "八月我去连中上课了。", effect: "fade", duration: 3300 },
    { text: "那是我第一次住校，特别不习惯。", effect: "fade", duration: 3300 },
    { text: "幸好每个星期都能和你打电话，随便聊聊班里的趣事，说说考试的成绩。", effect: "fade", duration: 6000 },
    { text: "每次听到你甜甜的声音，所有的烦躁和不安就都消失了。", effect: "fade", duration: 5000 },
    { text: "能和你分享我的生活，给我带来了莫大的慰藉。", effect: "fade", duration: 4500 },
    { text: "我好希望，可以每天和你聊聊天。。。", effect: "fade", duration: 6000 },
    { text: "听听你的声音，希望那样的日子能一直继续下去。", effect: "fade", duration: 5000 },
    { text: "再后来，你还是来了连中复读。", effect: "fade", duration: 3300 },
    { text: "我知道，你一定花了很大的力气才说服家里人。", effect: "fade", duration: 5500 },
    { text: "不管你是怎么做的，你没有因为一次考试放弃，还是选择对自己的人生负责", effect: "fade", duration: 5500 },
    { text: "这份为了自己人生拼尽全力的坚持和勇气，真的特别了不起。", effect: "fade", duration: 5000 },
    { text: "我不知道你最后去了哪所学校，也不知道结果怎么样，但这些都不重要。", effect: "fade", duration: 6000 },
    { text: "重要的是，你身上这份不服输的韧劲，对自己人生负责的态度，", effect: "fade", duration: 6000 },
    { text: "会一直陪着你，走很远很远的路。", effect: "fade", duration: 5000 },
    { text: "写这些话的时候，我删删改改了很多次。", effect: "fade", duration: 4500 },
    { text: "其实我的初衷特别简单：就是想在儿童节这天", effect: "fade", duration: 3500 },
    { text: "让你什么都不用想，开开心心地过一天。", effect: "fade", duration: 6000 },
    { text: "也想顺便说说我自己。", effect: "fade", duration: 3000 },
    { text: "我一直都知道，只要我想做到的事，就一定能做到。", effect: "fade", duration: 4000 },
    { text: "我从来都不缺想法，更不缺行动力。", effect: "fade", duration: 4000 },
    { text: "从高一到现在，我可以像个旁观者一样，安安静静地观察一切", effect: "fade", duration: 4500 },
    { text: "；也可以站上讲台，在全班面前弹吉他唱歌。", effect: "fade", duration: 4500 },
    { text: "高三复读那年，我在课前五分钟讲了整整一节课，给很多同学带去了高考的力量。", effect: "fade", duration: 7000 },
    { text: "老师说，如果我当老师，一定会是教育界的荣光，这句话我一直记到现在。", effect: "fade", duration: 8000 },
    { text: "对待喜欢的人，我也会义无反顾。", effect: "fade", duration: 3300 },
    { text: "高考考试当天复习那么紧张的时候，我还是会花好几节课的时间给你写信，只想哄好，那天生气的你。", effect: "fade", duration: 6000 },
    { text: "我觉得在待人接物这方面，我一直做得都挺好的。", effect: "fade", duration: 4000 },
    { text: "对待感情，我因为专一，拒绝了几个喜欢我的人，我已经做到了我能做到的最好。", effect: "fade", duration: 4000 },
    { text: "我知道我本来就很好，本来就有很多人喜欢我，很多人愿意和我做朋友。", effect: "fade", duration: 5000 },
    { text: "我从来不觉得，用心对待别人、给别人带去好的体验、让别人感受到我的温柔和真诚是一件错事。", effect: "fade", duration: 5000 },
    { text: "只是那有些过于消耗我的精力了，现在为了我自己，我该收收心了。", effect: "fade", duration: 5000 },
    { text: "我要把更多的注意力，放在自己身上，放在自己的成长上。", effect: "fade", duration: 4500 },
    { text: "还是想聊聊你", effect: "fade", duration: 3300 },
    { text: "我觉得美婷骨子里是个特别要强的人。", effect: "fade", duration: 3500 },
    { text: "偶尔会因为内心的拧巴，口是心非，说出两句和自己内心真实想法相悖的话。", effect: "fade", duration: 4000 },
    { text: "你肯定下意识想说，什么时候我怎么不知道？", effect: "fade", duration: 4000 },
    { text: "我才不跟你较真，哈哈，你那么较真看不懂别人的开玩笑还挺可爱的。", effect: "fade", duration: 5000 },
    { text: "你对别人的评价有时候也会很敏感，嘴上总是装作淡淡的，可心里却会暗自在意。", effect: "fade", duration: 4000 },
    { text: "或许是性格使然，明明很在意，", effect: "fade", duration: 4000 }, { text: "却会花很短的时间假装把自己说服，表面上看起来真的不在意了。", effect: "fade", duration: 5000 },

    { text: "你努力的动力，或许很多时候都不是什么远大的理想，而是害怕失去当下拥有的，还有那些掌控感", effect: "fade", duration: 5500 },
    { text: "你希望周围的一切都能安安稳稳，都能被自己掌控，只有这样，你才能有安全感。", effect: "fade", duration: 5000 },
    { text: "取得某些成就的时候，你会开心很久，可转眼就会开始焦虑，怕自己一旦松懈下来，就会掉下去。", effect: "fade", duration: 6000 },
    { text: "但是你心里最想做的事，其实就是安安静静待在自己的舒适圈里躺着，什么都不干。", effect: "fade", duration: 6000 },
    { text: "或许躺不了半天，内心的谴责就会涌上来，写好计划怎么看书学习。", effect: "fade", duration: 3300 },
    { text: "你会看一些爽文或是看剧放松自己，也会刷到各种好的文学文字去激励自己，或是学习里面的心态。", effect: "fade", duration: 3300 },
    { text: "就这样不断在理想和现实之间摇摆，把自己搞得很累很累。", effect: "fade", duration: 3300 },
    { text: "但也正是这份拧巴，让你从来没有真正放弃过自己。", effect: "fade", duration: 5000 },
    { text: "或许我说的不完全准确，我也想理解你", effect: "fade", duration: 4000 },
    { text: "你希望有人能懂你吗，还是害怕暴露真实的自己，不会被人接纳", effect: "fade", duration: 5000 },
    { text: "你说我有点恋旧，说我们只有以前可以聊了。", effect: "fade", duration: 3300 },
    { text: "虽然不想承认，但或许真的是这样吧。", effect: "fade", duration: 3300 },
    { text: "真的很久没见你了，线下遇到的话，会茫然吗，会害羞吗，", effect: "fade", duration: 5000 },
    { text: "还会不会像线上一样各种怼我", effect: "fade", duration: 3300 },
    { text: "其实你也是个特别重感情的人啊。", effect: "fade", duration: 4000 },
    { text: "我记错你生日的时候，你会吃醋生闷气，记仇记好久哈哈哈；", effect: "fade", duration: 4500 },
    { text: "我给你写贺卡的时候，你会提前写好回信，", effect: "fade", duration: 4500 },
    { text: "然后在朋友面前小心翼翼地把卡片倒置，遮住文字再交给我。", effect: "fade", duration: 4500 },
    { text: "这些小细节，我其实都看在眼里，记在心里。", effect: "fade", duration: 4500 },
    { text: "你好像不太会处理感情上的事，早就习惯了什么都自己解决，不喜欢麻烦别人。", effect: "fade", duration: 6000 },
    { text: "这当然是你的优点，特别自立自强。", effect: "fade", duration: 4000 },
    { text: "只是，我真的不希望你把所有的情绪都压抑在心里。", effect: "fade", duration: 4500 },
    { text: "你是个很稳重很温柔的人，对吧？", effect: "fade", duration: 4000 },
    { text: "只是有时候，对关系越好的人，脾气反而越不好，一点都不温柔哈哈。", effect: "fade", duration: 5000 },
    { text: "但没关系啊，我会认真听你说的每一句话，", effect: "fade", duration: 3300 },
    { text: "会看你指责的地方我是不是真的有问题，。", effect: "fade", duration: 3500 },
    { text: "会去想你为什么会这么说，会去理解你背后真正想要的是什么", effect: "fade", duration: 4500 },
    { text: "而那些所谓的指责，对我来说就像云一样，风一吹就散了。", effect: "fade", duration: 3300 },
    { text: "你这点小敏感、小在意，反而让我觉得特别可爱。", effect: "fade", duration: 3300 },
    { text: "还记得那年你当着好多人的面吼我吗？", effect: "fade", duration: 3500 },
    { text: "我早就不记得你具体说了什么了。", effect: "fade", duration: 3300 },
    { text: "我只知道，在那个时候如果我在你心里一点分量都没有，", effect: "fade", duration: 4500 },
    { text: "你根本不会那么在意我，更不会对我发那么大的脾气。", effect: "fade", duration: 4500 },
    { text: "能被你这样在意，我已经很满足了，现在的你怎么看我，我觉得已经不重要了。", effect: "fade", duration: 7000 },
    { text: "或许 \"关系走到最后，不过是相识一场。", effect: "fade", duration: 5000 },
    { text: "行出自愿，事过无悔；不负遇见，不谈亏欠。\"", effect: "fade", duration: 5000 },
    { text: "所有的关系，本质上都是人生路上不同站点的同行者，没有人能陪谁走到时间的尽头。", effect: "fade", duration: 5000 },
    { text: "我们能在最青涩的年纪相遇，一起走过那段最难熬的高中时光，已经是莫大的缘分了。", effect: "fade", duration: 8000 },
    { text: "我当年对你的好，从来都不是为了要什么回报，", effect: "fade", duration: 5000 },
    { text: "只是那个时候的我，发自内心地想让你开心。", effect: "fade", duration: 5000 },
    { text: "仅此而已。", effect: "fade", duration: 3300 },
    { text: "「树叶 又要散落了」", effect: "fade", duration: 2500 },
    { text: "「回想以前 没那么累」", effect: "fade", duration: 2500 },
    { text: "「现在的白发和皱纹匹配 ，也是一种美」", effect: "fade", duration: 2500 },
    { text: "现在的日子，或许没有那么如意吧。", effect: "fade", duration: 3300 },
    { text: "我知道，美婷的适应能力很强，这不算什么不如意", effect: "fade", duration: 5000 },
    { text: "可要强的你，从来都不愿意在别人面前露出半点脆弱。", effect: "fade", duration: 4000 },
    { text: "我说你应该不会和我聊你的工作，你突然说 \"你看我鸟你吗\"", effect: "fade", duration: 5000 },
    { text: "后来一看有些粗鲁，却也真实得可爱。", effect: "fade", duration: 4000 },
    { text: "不想跟我说也没关系的，不管你怎么样，我都不会看轻你，", effect: "fade", duration: 4500 },
    { text: "因为你是一个正直的人，一个自强自立的人，一个初入社会，努力融入工作，适应生活。", effect: "fade", duration: 5500 },
    { text: "或许是因为你内心的不服输，有时候会不会连你自己都看不起自己", effect: "fade", duration: 4500 },
    { text: "所以才会突然竖起防御的刺，用狠话来保护自己。", effect: "fade", duration: 4000 },
    { text: "我不会因为这些就看不起谁，相反，我一直都觉得你特别勇敢。", effect: "fade", duration: 4500 },
    { text: "你一个人在远离家乡的城市生活，不靠爸妈的支撑，也不靠亲戚的帮衬，把自己照顾得挺好。", effect: "fade", duration: 6000 },
    { text: "或许在家里也经常帮家里干活，一个女孩子家家的，感觉你小小一个有大大的能量哈哈，", effect: "fade", duration: 6000 },
    { text: "你在学校有做了很长时间的志愿者，当时听你说你的志愿者证200个小时了似乎", effect: "fade", duration: 5000 },
    { text: "我觉得你好厉害，动手能力很强。", effect: "fade", duration: 3500 },
    { text: "高三毕业就去打工赚钱，大学毕业靠自己的工资买了电脑，换了好几个手机。", effect: "fade", duration: 5000 },
    { text: "你在那个陌生的城市坚持了这么久，慢慢习惯了那里的生活", effect: "fade", duration: 4500 },
    { text: "应该已经可以把工作做得井井有条，最终在那里站稳了脚跟。", effect: "fade", duration: 3500 },
    { text: "刚开始的时候，压力一定很大吧？一定也有过迷茫和无助的时候吧？", effect: "fade", duration: 3500 },
    { text: "可你什么都没说，一个人全都熬过来了。", effect: "fade", duration: 3500 },


    { text: "我知道，你喜欢音乐，以前也经常画画，", effect: "fade", duration: 3500 },
    { text: "你有很多爱好，喜欢尝试新鲜事物。", effect: "fade", duration: 3500 },

    { text: "这一点在学习上或许算不上优势，但我相信", effect: "fade", duration: 4000 },
    { text: "这些爱好一定会在未来，给你的人生带来更多的可能性。", effect: "fade", duration: 4000 },
    { text: "你每天作息那么晚，天天把 \"摆烂\" 挂在嘴边，却一直坚持着练字的习惯。", effect: "fade", duration: 6000 },
    { text: "我知道，你不是不努力，只是有时候被环境限制了。", effect: "fade", duration: 4000 },
    { text: "你一直在用你自己的方式提升自己，也曾想过把自己的那些爱好融入生活，", effect: "fade", duration: 4000 },
    { text: "用自己的方式去对抗这个世界，只是因为一些现实的原因，没能坚持下去。", effect: "fade", duration: 5000 },
    { text: "没关系的，人生的时间还很长，我们要走的路还很远。", effect: "fade", duration: 5000 },
    { text: "你不是真的想摆烂，我都知道。", effect: "fade", duration: 3300 },
    { text: "说一句 \"自己很棒\" 好不好？", effect: "fade", duration: 7000 },
    { text: "美婷，你真的很已经很厉害了。", effect: "fade", duration: 3300 },
    { text: "会计这一行，工资本来就不高，不要因此看轻自己。", effect: "fade", duration: 5000 },
    { text: "你要知道，普通人拥有百万存款的平均年龄是五十多岁，不是二十多岁", effect: "fade", duration: 5000 },
    { text: "；普通人买房的平均年龄是三十五岁，不是二十多岁", effect: "fade", duration: 4000 },
    { text: "普通人买房的平均年龄是三十五岁，不是二十多岁；", effect: "fade", duration: 3500 },
    { text: "深耕一个行业需要七年，不是几个月", effect: "fade", duration: 3500 },
    { text: "很多人四十多岁，才真正找到自己的人生方向。", effect: "fade", duration: 3300 },
    { text: "把自己当成一颗小种子好不好？", effect: "fade", duration: 3500 },
    { text: "一颗亟待雨水、渴望破土生长的种子。", effect: "fade", duration: 3500 },
    { text: "你现在要做的，就是耐心等待，保持乐观，保存好自己向上的心态。", effect: "fade", duration: 5500 },
    { text: "工作经验和时间的积累，就是滋养你的养料。", effect: "fade", duration: 5500 },
    { text: "你只需要好好照顾自己，静静等待属于你的那场雨，然后破土而出，长成你想要的样子。", effect: "fade", duration: 8000 },
    { text: "以前我一直以为，努力可以改变所有事，觉得 \"命运\" 只是人没办法的时候才会说的借口。", effect: "fade", duration: 6500 },
    { text: "但走过很多路之后才慢慢明白，人生本来就有它自己的轨迹，很多人和事的结果，其实早就已经注定了。", effect: "fade", duration: 7000 },
    { text: "不过，相信命运并不代表向它妥协。", effect: "fade", duration: 3500 },
    { text: "坦然接受所有的相聚和离别，不慌不忙、不忘初心地向前走。", effect: "fade", duration: 3500 },
    { text: "坦然接受所有的相聚和离别，不慌不忙、不忘初心地向前走。", effect: "fade", duration: 3500 },
    { text: "走好属于自己的每一段路，就已经足够了。", effect: "fade", duration: 3300 },
    { text: "爱自己，是终身浪漫的开始哦。", effect: "fade", duration: 3300 },
    { text: "你爱自己的程度，决定了谁能走进你的人生。", effect: "fade", duration: 3500 },
    { text: "如果我只爱自己 20%，那么当有人带着 30% 的爱出现时，我就会轻易被打动，误以为那就是真爱。", effect: "fade", duration: 6000 },
    { text: "但如果我能 100% 地爱自己，那么出现的人，也必须带着 100% 甚至更多的爱，才配站在我面前。", effect: "fade", duration: 6000 },
    { text: "把自己爱到满分，才能筛选掉所有打折的真心。", effect: "fade", duration: 4500 },
    { text: "以后，我会更加关注自己的情绪和想法，不再一味地退让和迁就。", effect: "fade", duration: 3500 },
    { text: "我不能总是为别人而活，对吧？", effect: "fade", duration: 3300 },
    { text: "也愿我们都能在善待他人的同时，给自己百分百的爱。", effect: "fade", duration: 5000 },
    { text: "「青春 是一个梦」", effect: "fade", duration: 3300 },
    { text: "「人生 如一阵春风」", effect: "fade", duration: 3300 },
    { text: "「不经意的飘过 境界蓦然辽阔」", effect: "fade", duration: 3300 },
    { text: "青春就像一场梦，我打了个盹，就错过了你的大学三年。", effect: "fade", duration: 3300 },
    { text: "我们一定还有缘分吧？", effect: "fade", duration: 3300 },
    { text: "明明当时那么决绝的想离开你，但是你一回头，轻轻的敲一下门，我还是开了。", effect: "fade", duration: 6000 },
    { text: "或许你只是想找个人倾诉一下，\"联系的老朋友很少，老同学里就基本跟我聊聊\"。", effect: "fade", duration: 6000 },
    { text: "好噢，不管我们有没有缘分，我觉得就这样不强求、不索求，慢慢走下去，时间总会给我们答案。", effect: "fade", duration: 6000 },
    { text: "我希望你可以把我当成一个好朋友来看，而不是一个追求者。", effect: "fade", duration: 4500 },
    { text: "我不是你的追求者，我做这些事也不是为了讨好你。", effect: "fade", duration: 4000 },
    { text: "我只是想验证一下，我的想法和我的能力，到底能不能匹配。", effect: "fade", duration: 4000 },
    { text: "现在我知道了：只要我很想很想做一件事，就一定会尽全力去做，边想边做，而不是一味地空想。", effect: "fade", duration: 6000 },
    { text: "只要我想，就一定能做到。我相信我自己。", effect: "fade", duration: 3300 },
    { text: "你说过，我很适合写小说，因为我的想法很多。", effect: "fade", duration: 4300 },
    { text: "我还有很多其他的优点，当我真正找到自己的主体性时，就能更好地向前走了。", effect: "fade", duration: 5000 },
    { text: "我才不想听你说什么 \"没感觉\"、\"凭直觉\" 之类的话。", effect: "fade", duration: 4500 },
    { text: "为什么？因为我们已经四年没见了。", effect: "fade", duration: 4000 },
    { text: "我不知道你现在住在哪里，不知道你这三年经历了什么", effect: "fade", duration: 3300 },
    { text: "不知道你现在的样子，不知道你现在的声音，", effect: "fade", duration: 3300 },
    { text: "也不知道你养成了什么新的习惯。", effect: "fade", duration: 3300 },
    { text: "我只给你看到了我想给你看到的东西，仅凭四年前的印象谈感觉，不过是刻舟求剑罢了。", effect: "fade", duration: 6000 },
    { text: "我想，我现在并不适合谈恋爱。", effect: "fade", duration: 3300 },
    { text: "我马上就要毕业了，正处在人生的起步阶段。", effect: "fade", duration: 4000 },
    { text: "这几年，我应该把所有的精力都放在学习和工作上，赚钱才是第一要义。", effect: "fade", duration: 5000 },
    { text: "只有赚了钱，才能给家人给喜欢的人更好的生活。", effect: "fade", duration: 5000 },

    { text: "我想，你现在大概也不适合谈感情吧。", effect: "fade", duration: 3300 },
    { text: "每天的工作已经够累了，你最需要的是休息，对吧？", effect: "fade", duration: 3300 },
    { text: "你对待工作应该很认真，一定累坏了吧。", effect: "fade", duration: 4500 },
    { text: "你也不是真的想摆烂，你一直在用你自己的方式努力。", effect: "fade", duration: 5000 },
    { text: "只是一个累坏了的人，根本没有多余的精力去给别人什么情感。", effect: "fade", duration: 4500 },
    { text: "你需要的，是一个简简单单、没有任何压力的人。", effect: "fade", duration: 4500 },
    { text: "不需要你付出感情，也不需要你刻意回应。", effect: "fade", duration: 3300 },
    { text: "就像憨豆先生的小熊一样，安安静静地躺在床上，或者被憨豆先生带着出去玩，任由他爱护着、摆弄着。", effect: "fade", duration: 6000 },
    { text: "它没有感情，也不需要感情，只需要在憨豆先生需要的时候，陪在他身边就好。", effect: "fade", duration: 5500 },
    { text: "憨豆先生很爱它，对它很好。", effect: "fade", duration: 3300 },
    { text: "世界上真的有这种小熊吗？或许吧。", effect: "fade", duration: 6000 },
    { text: "另外的，或许改变不了的事情，就随缘吧。", effect: "fade", duration: 4000 },
    { text: "交给时间去沉淀，我们只要认真做好自己的事情就好。", effect: "fade", duration: 4500 },
    { text: "剩下的，都交给时间。", effect: "fade", duration: 4500 },
    { text: "\"昨天变成了今天 ，过去变成了现在 ，未来刚才来 ，它从何而来 ，放下那 曾经 ，留下那 痕迹 ，前方的你 别忘了自己\"", effect: "fade", duration: 8000 },
    { text: "\"成长是永远 离别是空悬 在千寻之外 我依然存在\"", effect: "fade", duration: 3800 },
    { text: "你已经努力了，已经尽力了，做到最好", effect: "fade", duration: 3800 },
    { text: "或许美婷在社会中变得现实了，但是你在我这里永远是小孩子", effect: "fade", duration: 3800 },
    { text: "在我这里没有什么地位，学历，工资，权利", effect: "fade", duration: 4000 },
    { text: "伤心了，受伤了，我在这里听着，陪着", effect: "fade", duration: 4500 },
    { text: "当然是我不忙的情况下，谢谢你，我学会了把心思放在自己身上多一点我会变得更好哦，为了我自己。", effect: "fade", duration: 6500 },
    { text: "在这个时代，我们都太在意结果了，却忘了只有当下这一刻，才是漫长岁月中最珍贵的。", effect: "fade", duration: 7500 },
    { text: "不要太看重眼前的苦难，而忘记珍惜自己的羽毛。", effect: "fade", duration: 4000 },

    { text: "今天是儿童节。", effect: "fade", duration: 3300 },
    { text: "就把所有的烦恼都暂时放下吧，做一天无忧无虑的小朋友。", effect: "fade", duration: 5000, music: "/static/uploads/music/方大同 - 特别的人.flac" }
];

export default meitingChildrenDayConfig;